# contrib-wide Makefile include file, generated automatically with
# ./configure --fastjet-config=/uscms_data/d2/rappocc/fastjet/fastjet_cms/install/bin/fastjet-config --prefix=/uscms/home/rappocc/nobackup/fastjet/fastjet_cms/fastjet-contrib CXXFLAGS=-I/uscms_data/d2/rappocc/fastjet/fastjet_cms/install/include -I/uscms_data/d2/rappocc/fastjet/fastjet_cms/install/tools
CXXFLAGS=-I/uscms_data/d2/rappocc/fastjet/fastjet_cms/install/include -I/uscms_data/d2/rappocc/fastjet/fastjet_cms/install/tools
FASTJETCONFIG=/uscms_data/d2/rappocc/fastjet/fastjet_cms/install/bin/fastjet-config
PREFIX=/uscms/home/rappocc/nobackup/fastjet/fastjet_cms/fastjet-contrib
install_script = $(SHELL) ../utils/install-sh
check_script = ../utils/check.sh
